<a href="https://colab.research.google.com/github/Sushmithabp/Workshop-on-python-programming-in-DA-and-ML/blob/master/DAY3_SESSION2_EXERCISE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.Write a Pandas program to create and display a one-dimensional array using series containing event numbers upto 10000
tip : use List Comprehension ds = pd.Series([0,2, 4, 6, 8..... 10000])

In [1]:
import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)

0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64


#2.Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type


In [2]:
import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)


0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


#3.Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [3]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


4.Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 

In [4]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


#5.Write a Pandas program to convert a NumPy array to a Pandas series.

In [5]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


6.Write a Pandas program to convert a given Series to an array.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [6]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


#7.Write a Pandas program to sort a given Series.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [7]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
a.sort()
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '300.12' '400' '400' '500' 'great' 'is' 'language'
 'python']


#8.Write a Pandas program to create a subsets of a given series based on value and condition.
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000] value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5

In [8]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


#9.Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

In [9]:
import pandas as pd
s = pd.Series(data = [x for x in range(1000) if x%2==0])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64
Mean of the said Data Series:
499.0
Standard deviation of the said Data Series:
288.9636655359978


#10.Write a Pandas program to get the elements of an array values into column-wise.
Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}

In [10]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


#11.Write a Pandas program to display the first 10 rows of the DataFrame for any particular three field

In [25]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
print(df.iloc[:3])


!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials


auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

downloaded = drive.CreateFile({'id':'1hzxXR0uL-JosrCjV6JNn4g9FRMttT5rP'}) # replace the id with id of file you want to access
downloaded.GetContentFile('movies_metadata.csv')
import pandas as pd
xyz = pd.read_csv('movies_metadata.csv') 
print(xyz.head(1))


First three rows of the data frame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


ApiRequestError: ignored

#12.Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields #(movie_metadata.csv file).


In [22]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
seventh_movie = df.iloc[3]
print("Details of the seventh movie:")
print(seventh_movie)

Details of the seventh movie:
adult                                                                False
belongs_to_collection                                                  NaN
budget                                                            16000000
genres                   [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
homepage                                                               NaN
id                                                                   31357
imdb_id                                                          tt0114885
original_language                                                       en
original_title                                           Waiting to Exhale
overview                 Cheated on, mistreated and stepped on, the wom...
popularity                                                         3.85949
poster_path                               /16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg
production_companies     [{'name': 'Twentieth Century Fox Film Corpora

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


#13.Write a Pandas program to sort the DataFrame based on title_year from dataset of movie_metadata.csv for any particular three fields

In [23]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
result = df[['release_date', 'genres']]
print("Details of release_date and genres:")
print(result)

Details of release_date and genres:
      release_date                                             genres
0       1995-10-30  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1       1995-12-15  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2       1995-12-22  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3       1995-12-22  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4       1995-02-10                     [{'id': 35, 'name': 'Comedy'}]
...            ...                                                ...
45461          NaN  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
45462   2011-11-17                      [{'id': 18, 'name': 'Drama'}]
45463   2003-08-01  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
45464   1917-10-21                                                 []
45465   2017-06-09                                                 []

[45466 rows x 2 columns]


/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


#
14.Write a Pandas program to sort the DataFrame based on country and language from dataset of movie_metadata.csv

In [24]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
# Create a smaller dataframe
small_df = df[['title', 'release_date', 'budget', 'revenue', 'runtime']]
result = small_df.sort_values('release_date')
print("DataFrame based on country and language.")
print(result)

DataFrame based on country and language.
                                                title  ... runtime
19730                                             NaN  ...     NaN
29503                                             NaN  ...     NaN
34940                                Passage of Venus  ...     1.0
34937                      Sallie Gardner at a Gallop  ...     1.0
41602                                 Buffalo Running  ...     1.0
...                                               ...  ...     ...
45148                                 Engineering Red  ...    76.0
45203  All Superheroes Must Die 2: The Last Superhero  ...    74.0
45338                  The Land Where the Blues Began  ...     0.0
45410                                           Aprel  ...     NaN
45461                                          Subdue  ...    90.0

[45466 rows x 5 columns]


/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


#.Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable

In [18]:
import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x) 


Original Array:
[[0.14201594 0.18249684 0.38491657 0.64979003]
 [0.57731785 0.72123635 0.38458883 0.74644714]
 [0.0131399  0.49308894 0.56620758 0.7473248 ]
 [0.47430509 0.84871786 0.70380767 0.88193038]]


#16.Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

In [19]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)



Original Array:
[[0.60812121 0.41010998 0.151805   0.68505444 0.59719217 0.06488585
  0.58274974 0.98651805 0.25130424 0.18579795]
 [0.21838411 0.66897804 0.16354295 0.85911328 0.97680903 0.88720227
  0.45344877 0.49695572 0.38010019 0.43087997]
 [0.9270103  0.02010085 0.90847349 0.94572962 0.34211572 0.8666569
  0.62622801 0.66515213 0.18451638 0.52780668]
 [0.15821636 0.56012077 0.73438839 0.15282133 0.33359337 0.80011377
  0.88119581 0.38637897 0.34082481 0.04257068]
 [0.97535144 0.16238954 0.42542923 0.78432209 0.92586876 0.30168073
  0.04481119 0.70142746 0.89176146 0.12955469]
 [0.96778286 0.61650315 0.09597826 0.41406844 0.01828256 0.67111435
  0.47897745 0.06149382 0.18489802 0.55250936]
 [0.94140192 0.99006843 0.19471888 0.40694829 0.85577878 0.42832858
  0.77245685 0.28596633 0.01337106 0.11232953]
 [0.96166596 0.49636077 0.49222066 0.80945409 0.23952713 0.72834136
  0.60658111 0.39205678 0.5241783  0.53342541]
 [0.32675607 0.56012499 0.72340433 0.64863236 0.40328705 0.369785

#17.Write a NumPy program to generate 8 random integers between 100 and 300

In [20]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[277 219 250 252 156 281 141 242]


#18.Write a NumPy program to create a random integer nos of size 20 and sort it

In [21]:
import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.19708862 0.02889926 0.58307057 0.00973705 0.9999958  0.57485088
 0.33470432 0.37029373 0.31793777 0.15767305 0.80209717 0.17152069
 0.74269633 0.45540328 0.90061382 0.2165895  0.13827425 0.14618564
 0.48412342 0.07171671]
Sorted array:
[0.00973705 0.02889926 0.07171671 0.13827425 0.14618564 0.15767305
 0.17152069 0.19708862 0.2165895  0.31793777 0.33470432 0.37029373
 0.45540328 0.48412342 0.57485088 0.58307057 0.74269633 0.80209717
 0.90061382 0.9999958 ]


#19.Write a Pandas program to get the details of the movies record number divisable by 5 of the DataFrame (movie_metadata.csv file)

In [29]:
import pandas as pd
import numpy as np
df = pd.read_csv('movies_metadata.csv')
small_df = df[['title','budget','release_date']]
for i in range(1,len(df)+1):
  if i%5==0:
    print(f"{small_df.iloc[i]}\n")

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Streaming output truncated to the last 5000 lines.
budget                     0
release_date      2015-08-19
Name: 40470, dtype: object

title              El Paso
budget                   0
release_date    1949-03-22
Name: 40475, dtype: object

title           Tammy Tell Me True
budget                           0
release_date            1961-07-26
Name: 40480, dtype: object

title              Divines
budget             2791874
release_date    2016-08-31
Name: 40485, dtype: object

title            The Speak
budget                   0
release_date    2011-01-06
Name: 40490, dtype: object

title           Billy Lynn's Long Halftime Walk
budget                                 40000000
release_date                         2016-11-10
Name: 40495, dtype: object

title           Olmo & the Seagull
budget                           0
release_date            2015-11-05
Name: 40500, dtype: object

title                Naked
budget                   0
release_date    2014-11-07
Name: 40505, dtyp

#Write a Pandas program to find the mean and standard deviation, maximum and minimum of the data of 50 students Python marks stored in a CSV file called Python_mark.csv( you have to create the file yourself like rollno,mark for 50 records)

In [34]:
import pandas as pd
df = pd.read_csv('student_marks.csv')
print("file content: ",df)
print ('Mean : ' + str(df['marks'].mean()))
print ('S.D: ' + str(df['marks'].std() ))
print ('Minimum : ' + str(df['marks'].min()))
print ('Maximum : ' + str(df['marks'].max()))

file content:      marks  rollno
0      11   111.0
1       2   111.0
2      22  1111.0
3      33    66.0
4       3    44.0
5       0     4.0
6      99     4.0
7       0    44.0
8      77    54.0
9     888    44.0
10     11   444.0
11     11   444.0
12     33   444.0
13     55   444.0
14     44  4444.0
15     33    55.0
16     11     5.0
17     11    43.0
18      2     5.0
19     22   555.0
20     55    33.0
21    555   333.0
22     22   333.0
23    333   333.0
24     33    11.0
25    444    22.0
26      4  2222.0
27     44   333.0
28     55   445.0
29     44     0.0
30     44    55.0
31    444    44.0
32     44    44.0
33     55    66.0
34     66     6.0
35    555     6.0
36     66    66.0
37     55     7.0
38    555     8.0
39     55     8.0
40     66   999.0
41    666   888.0
42     66     0.0
43      6     0.0
44     66    11.0
45      6    11.0
46    666     NaN
47     66    22.0
48     66     1.0
Mean : 134.08163265306123
S.D: 219.11496570813895
Minimum : 0
Maximum : 888
